#!/bin/zsh

autoload zmv

alias su='sudo -s'

alias cless='less -R'
alias devlog='less -R log/development.log'
alias devtail='tail -n 1000 log/development.log | less -R'

alias du="du -hc"
alias dus="du -hcs"
alias df="df -h"

alias ls="ls -G"
alias la="ls -Ga"
alias ll="ls -Ghl"
alias lla="ls -Ghla"
alias lal="ls -Ghla"

alias bx="bundle exec"
alias cuke="bundle exec cucumber"
alias spek="bundle exec rspec"
alias rakk="bundle exec rake"
alias con="bundle exec script/console"
alias cdb="cd /Developer/betterplace"

alias rediss="redis-server /opt/local/etc/redis.conf"

alias nscr='screen -h 5000 -S'
# alias rm='rm -i'


